<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Education' => 'Обучение',
  'Create new anket' => 'Создать тест',
  'Name' => 'Название',
  'Space' => 'Пространство',
  'Date Start' => 'Дата начала',
  'Date End' => 'Дата конца',
  'Active' => 'Активность',
  'Results' => 'Результаты',
  'Edit' => 'Редактировать',
  'Useful information' => 'Полезная информация по тесту',
  'Go test' => 'Пройти тест',
  'Back' => 'Назад',
  'Your result' => 'Ваш результат:',
  'User' => 'Пользователь',
  'Date' => 'Дата',
  'Time' => 'Время',
  'Count' => 'Количество',
  'No results' => 'Нет результатов',
  'You have' => 'Вам осталось',
  'You results' => 'Ваш Результат',
  'Restart test' => 'Пройти тест cнова',
  'Answer is' => 'ответа из',
  'Select many answer' => 'Выберите один или несколько ответов',
  'Sort answer priority' => 'Расставте ответы по приоритету',
  'Next' => 'Далее',
  'Test now' => 'Существующие тесты',
  'Time go test' => 'Время прохождения (минут):',
  'All tests' => 'Все тесты',
  'Test start' => 'Пройти Тест'

);
