<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Page title' => 'Название',
  'Edit anket' => 'Редактирование',
  'Create anket' => 'Создать анкету',
  'Name' => 'Название',
  'Has one' => 'Один из',
  'Has many' => 'Много из',
  'Prioretet' => 'Расставить приоритет',
  'Description' => 'Описание',
  'Space' => 'Пространства',
  'Date Start' => 'Дата начала',
  'Date End' => 'Дата конца',
  'Duration' => 'Продолжительность (минут)',
  'Visibility' => 'Активность',
  'Questions' => 'Вопросы',
  'You no questions' => 'У вас нет добавленных вопросов',
  'Question' => 'Вопрос',
  'Delete question' => 'Удалить вопрос',
  'Variant' => 'Вариант ответа',
  'Has one' => 'Один из',
  'Has many' => 'Много из',
  'Priorytet' => 'Расставить приоритет',
  'Answer' => 'Ответы',
  'Add question' => 'ДОБАВИТЬ ВОПРОС',
  'Save' => 'Сохранить',
  'Delete' => 'Удалить',
  'Information' => 'Информация',
  'Delete questions' => 'Удалить вопрос',
  'Many' => 'Пройти несколько раз',
  'Delete informations' => 'Удалить информацию',
  'Add Informations' => 'Добавить информацию',
  'Your result' => 'Ваш результат',
  
);
